theme = "mysonokai"

[editor]
cursorline = true
gutters = ["diagnostics", "diff"]
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[keys.normal."space"]
C-f = "file_picker_in_current_buffer_directory"
