[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "lua"
auto-format = true

[language.config.Lua.workspace]
library = [
  "/Users/arvidbjurklint/.hammerspoon/Spoons/EmmyLua.spoon/annotations",
]

[language.config.Lua.diagnostics]
globals = ["hs"]
