[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "lua"
auto-format = true

[language-server.lua-language-server.config.Lua.workspace]
library = [
  "/Users/arvidbjurklint/.hammerspoon/Spoons/EmmyLua.spoon/annotations",
]

[language-server.lua-language-server.config.Lua.diagnostics]
globals = ["hs"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "starlark"
file-types = ["bzl", "bazel", "BUILD", "star", "Tiltfile"]
