[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }

[[language]]
name = "toml"
auto-format = true
