[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "lua"
auto-format = true

[language-server.lua-language-server.config.Lua.workspace]
library = [
  "/Users/arvidbjurklint/.hammerspoon/Spoons/EmmyLua.spoon/annotations",
]

[language-server.lua-language-server.config.Lua.diagnostics]
globals = ["hs"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "starlark"
file-types = ["bzl", "bazel", "BUILD", "star", "Tiltfile"]

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "yaml"
formatter = { command = 'yamlfmt', args = ["-"] }
auto-format = true

[language-server.yaml-language-server.config.yaml]
completion = true
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
kubernetes = "*.yaml"
